apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sgma-system
  name: auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: salaheddine122/soge-system-authentication-service:AUTH-SERVICE-v1.1.0
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: auth-service-configmap
          - configMapRef:
              name: active-profile-configmap
        ports:
        - containerPort: 8081

        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        #resources:
         # requests:
          #  memory: "64Mi"
           # cpu: "50m"
          #limits:
           # memory: "128Mi"
            #cpu: "100m"
      imagePullSecrets:
        - name: regcred