apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8081
  selector:
    app: {{ .Values.appName }}