# Generic Section
metadata:
  namespace: sgma-system
appname: socgen-ui
#Deployment Section
replicas: 4
resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"
dockersecretname: regcred
# Ingress Section
ingresshostname: minikube-socgen-ui.socgen.com
tlsgeneratedsecretname: socgen-ui-cert
ingressname: nginx
clusterissuername: ca-issuer








