apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sgma-system
  name: config-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
      - name: config-service
        image: salaheddine122/soge-system-config-service:CONFIG-SERVICE-v1.0.0
        envFrom:
          - configMapRef:
              name: config-service-configmap
        ports:
        - containerPort: 9999

        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 9999
          initialDelaySeconds: 10
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 9999
          initialDelaySeconds: 10
          periodSeconds: 10
        #resources:
         # requests:
          #  memory: "64Mi"
           # cpu: "50m"
          #limits:
           # memory: "128Mi"
            #cpu: "100m"
      imagePullSecrets:
        - name: regcred