---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kc-db-credentials
  namespace: sgma-system
spec:
  encryptedData:
    KC_DB_PASSWORD: AgBKapHvor/I1z5uc49me3xwkPHoPdha+ol6Nd5D5ma2SsyyPZChGmoi82RMnuGWeeMGzos4cgzd90r5z3dC/OfQOwKsaOccvizzte3w4lUq7Xf1rV5DOzpDXbICdr6qCmAlpQMcfCTBOo9q3v5SE+2TrGmQ9SOlhDplPMGb12TVPuZWDTZ0i1KCgW0L6vQ716qqa/poNLa1uhObgp5ro1rJxliLqRAnzHXMt0lXdaaLmNtth7yGGnN9eVOH9hBhhJ2vLBCYKiWzeD8bturHglbdZ3B93tGzQTohkkf7TpYETLjVmN3n7ccb1HlozdqXQ+WmmmwlN8e5yNCpHyUkDYtG28zLxgDEfITqfLHdnmvM8e6z8VcnNc0gkyanr3AB7PxTyQiUdYwWeCNGjnVjtCZLu4StNwmRu2j157zHNCq2yj+lWYQcC75lnPuOAGgxk93p71OU+TNAYIqigwgXnoBChD8dF+Y3pyv4C4ysSN+CAWt16nUGuRWSkjnLy/DyybA8F0XVpX7u6wDHQXqTmh2O426x/PB8NCm7xiXz2AHYPpnI35ZSOtb3TWMu6StdT2R0yXWHpFZmP3hbWSo1HjVAlz2SS5+1Mq7XoM0v9U8L194T/S2e2xuYIZPzCpSQoUUZ/P/vSxsjLsl/16plw+/0ljJhkg35FTLDQ97wX29L1lu6TYZ5sgzZAOye1tO8sndtzJUm/cqOZ1q6XGhTXW1GxAC0lsJyhV/Ifi7g8z+UMA==
    KC_DB_USERNAME: AgBRv++BtP0aOIU19SLrw8E08oncIwgWSLfbqvfrT+2BPyVHU30QJLAcPU/gsJD7y0m+40aEICWtdV6EJ7IRKaeSDyU7P1jfBn5CDgv3jUq8AJgc7tgZS9pv9EG5rpBXKIp36jGkeoe+pUrDS6RM2xAaLP2aJsZEFyEQ5HakH+cMJQvSlx+/nVJhZDYOEbiBJYQc+CdRxeEfVSREzY9YykmPx7Mr8BKUV2fs3xjwwoKk967HKaOyGJy+ai1IJtGNOmuDoErfXsslHq8sMnNW2P28G+f9b9ztBPo23NAfMlPEBG1lWY2kI3i5ihbheZMwEowDJZEBM+bNABLG063Wy86Ox8FEV534PRzOpVaGDz9TyW7GvrvRSOpCwoD4QFdYt97BU1cpXzZ4PXGxJzzhPJHU2r6kovuRU7V4MqDP17h4cOb80hqXJVVNwsfJMoZHWmS+IYj0j8Zkds0rinz1u3X/lGHQPRIHxBOEL7bsmfwZTyQxmffx6w3zIU7MCaMsGKyk1vfOVici+1Qn9MF35uY1WQahi+1M2lsKp7ilkw3u5GQ7uIoEksuvKz+6pfhBMofbQJ4Typa23I3kWm/yX0SYX0GQDJfcOmCrO8L6QD0JGCsbLrxWhh3ewwHv4yFfxb8t1I9aPTMGX5LbFbHw0i0Cb9sMQeJ5Y6pF3XMFPwnY9lVVJH8Rsqc6Qct9FUtT10QtaK8RWRBUwNioHsZI
  template:
    metadata:
      creationTimestamp: null
      name: kc-db-credentials
      namespace: sgma-system
    type: Opaque
