- name: Copy template to /tmp/ingress-nginx.yaml
  template:
    src:  ingress-nginx.yaml
    dest:  "/tmp/ingress-nginx.yaml"

- name: Run Ingress Controller
  shell: "kubectl apply -f /tmp/ingress-nginx.yaml"

- name: Disable validating webhook
  shell: "kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission"
    