apiVersion: v1
kind: Service
metadata:
  namespace: sgma-system
  name: admin-service
  labels:
    app: admin-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8765
  selector:
    app: admin-service