apiVersion: v1
kind: Service
metadata:
  namespace: keycloak
  name: keycloak-service
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
  selector:
    app: keycloak
  type: NodePort