apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.volumeNode }}
      containers:
      - name: {{ .Values.appName }}
        image: bitnami/minio:2024.4.6-debian-12-r0
        ports:
        - containerPort: 9000
        - containerPort: 9001
        env:
          {{- range $key, $value := .Values.minio.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "1Gi"
        volumeMounts:
        - name: {{ .Values.volumeName }}
          mountPath: {{ .Values.mountPath }}
          readOnly: false

      volumes:
      - name: {{ .Values.volumeName }}
        hostPath:
          path: {{ .Values.dataFileLocation }}
          type: DirectoryOrCreate
