apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appName }}-service
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      name: "internal-port"
      port: 80
      targetPort: 9000

    - protocol: TCP
      name: "dashboard-port"
      port: 9001
      targetPort: 9001
