apiVersion: v1
kind: Service
metadata:
  namespace: sgma-system
  name: auth-service
  labels:
    app: auth-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8081
  selector:
    app: auth-service