apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8089
  selector:
    app: {{ .Values.appName }}