- name: Generate and save join command
  command: kubeadm token create --print-join-command
  register: join_output
  when: inventory_hostname == MAIN_CONTROLPLANE

- name: save command in middle variable
  set_fact:
    join_command: "{{ join_output.stdout }}"
  when: inventory_hostname == MAIN_CONTROLPLANE

- name: save middle variable in workers nodes
  set_fact:
    transferred_token_command: "{{ hostvars[MAIN_CONTROLPLANE].join_command }}"
  when: inventory_hostname != MAIN_CONTROLPLANE

- name: Add workers
  shell: "{{ transferred_token_command }}"
  when: inventory_hostname != MAIN_CONTROLPLANE