apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sgma-system-viewer
  namespace: sgma-system
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sgma-system-viewer-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: sgma-system
roleRef:
  kind: Role
  name: sgma-system-viewer
  apiGroup: rbac.authorization.k8s.io
