---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: default
spec:
  encryptedData:
    MINIO_ACCESS_SECRET: AgASYcFaqLN4ua7p1gfqeUR+4+frezh8uwXZJtFVwWQWIzjJNiJdr3jQYwTtVhIbAsGbysH3JMqlnml2Xjf9LI+t0qg+udoXwqJqP2Uv4LkoknEGxJGOIjNDN1GUz7Od1q6UZ8YYwBs1NFTqD+DLn90ykARJtxHvH3O07KZVznq7qA6JgbzYo5De+IqbOQ4lyhUn+Y6hXzHJFrfvplMWn/BXS8rtbm+Dl2kPBset/yJ955jCGe/UjistwRqeDERSfcrT28a3WIJQaeaEc8Yl98ZZcOVCnhzOJ826hpvHM8RRP8+AJWx6qjAfDg6Mn10DxhraBp/QouR3Zexuj+bFm9GYJoFrAcDbUisRfKXZA+7o5CGIuqP9X15w+3SqZIutkvWVwH6RofVhLf2rb02eb+zBlq8O4FIB0/BqcHAW6t5ZJp6wXBwAsByE6lz0QJ43LxuQAd2p/+JBKx8jsCXRYjw735ilcO+UVRk7kl/XkqV6EIDc1t8REA/ywQnBVZVNc86ugKsxUr6JUMIe+pHwbEtZYmJ5SiLL93oSz6K4VEP5veVUyvsF3Z1jxdnUt1yK/X1ELKdREvvgWVfHuFAqGBaQDEfU6+dJhyekh4BjUzJjokalHJPiytw6sxNHQYwUn4OVikE1gKwup9meF6BzWmCqyuYDwWpX0udxgOWBAD1mNDINan8Yhqxqe+SkHQvl30lAkH5x/7+9JmpqsU581SHDbkLQiVd88a0=
    MINIO_ACCESS_USERNAME: AgCdvSB9+JXxeyHMuIZB08w8fA6boA30JeQmYLnJySi4GUZxxZXMRcR6YjTrmK0JbQodmtk0R5Gwz9ynqKBbHevLSY+ai5p/5vsOiQ9KN5Y0iz52yuxfCjqa0Tld5n+wmUcjz+ZQN/HdpPbXoq5NJT3BZBY402vOFh2l/XgSAtnSZTtNX/stOQoN8iZLdslaNYvKffWSTuJOflZwx9KwTuhZ4Fujd2VgmK2X3ib5DIkqk+Fl0l6u6QC6hbmZ+DWKT6vbxRO8cq8DC54rdhI0DtBOFeAmyH9EV29K/yhwE36dtgQLBkgy7lAqia0D8rK0ReruCIz3Upg7d/v4mgsYvXsvZ5IYJEP2mn0PSdTKNxeTO0yu4gPC+sb5WUUZu6kj9JC9myxET/u2zIY/RvDX4Oyu8oo81MLZtzOeZsJ6cL8DkteBKyQkytNXa0NTAB8Kp7dhN8I+wHJUSQYpZmMuTHBBuWWDfY2eqOL0aYKqyjabNtn12tpEAQzhxp3LLj1QM5ICd5DvoNpDqXKSn/PhTibMYGqTq0Ms4b/GJoDQfUiKie5Kevy4oYadWyh54UajmBGD9widX1V7Ua6PfIG68gWM6j7cEwSoMkXc0KUgD7is8CP2CMCuIVaYf6hYrSMGU+AXm6nEiELm0pXT5tT+WldoqMNrDzeDFH12SqOVbFI2w/BfjX8CYBuyvzt2BfH2rAQzE3AEM2Zm/fb7bEr0NKo=
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: default
    type: Opaque
