apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: keycloak
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.2
          command: ["/opt/keycloak/bin/kc.sh"]
          args: ["start"]
          env:
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: "true"

            - name: KC_HOSTNAME
              value: "minikube-keycloak.socgen.com"
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              value: "jdbc:postgresql://dpg-co6iu9kf7o1s73dk977g-a.oregon-postgres.render.com:5432/socgendefault"
            - name: KC_DB_USERNAME
              value: "socgen"
            - name: KC_DB_PASSWORD
              value: "tAGYwXJHQoLwMaqbeIYlSV5S0Qmncpcr"

            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY
              value: "edge"
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: "/etc/tls/tls.crt"
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: "/etc/tls/tls.key"
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          volumeMounts:
            - name: host-etc
              mountPath: "/etc/tls"
      volumes:
        - name: host-etc
          hostPath:
            path: "/etc/tls"
