apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: keycloak
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.2
          args: ["start-dev"]
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY
              value: "edge"
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: "/etc/tls/tls.crt"   # Update path to reflect subdirectory
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: "/etc/tls/tls.key"   # Update path to reflect subdirectory
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
          volumeMounts:
            - name: host-etc
              mountPath: "/etc/tls"   # Mount to a subdirectory within /etc
      volumes:
        - name: host-etc
          hostPath:
            path: "/etc/tls"
