apiVersion: v1
kind: ConfigMap
metadata:
  name: config-service-configmap
  namespace: sgma-system
data:
  ACTIVE_PROFILE: "default"
  SERVER_PORT: "9999"
  DISCOVERY_ENABLED: "false"
  CONFIG_GIT_URI: "https://github.com/Yahya-rabii/configrepo.git"
  #CONFIG_GIT_USERNAME: "Yahya-rabii"
  #CONFIG_GIT_PASSWORD: "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" # will change this later as a secret
  CONFIG_GIT_DEFAULT_LABEL: "master"
  EUREKA_REGISTRY_FETCH_INTERVAL_SECONDS: "5"
  EUREKA_REGISTER_WITH_EUREKA: "true"
  EUREKA_FETCH_REGISTRY: "true"
  EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: "http://discovery-service-service.sgma-system.svc.cluster.local/eureka/"
  EUREKA_INSTANCE_HOSTNAME: "config-service-service.sgma-system.svc.cluster.local"