server:
  port: 8888
  servlet:
    context-path: /
spring:
  application:
    name: Gateway
  cloud:
    gateway:
        routes:
          - id: client-service
            uri: lb://CLIENT-SERVICE
            predicates:
              - Path=/clients/**
          - id: contract-service
            uri: lb://CONTRACT-SERVICE
            predicates:
              - Path=/contracts/**
    discovery:
      enabled: true
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: Gateway
        display-name: Gateway
      - url: /CLIENT-SERVICE/v3/api-docs
        name: CLIENT Service
        display-name: CLIENT Service
      - url: /CONTRACT-SERVICE/v3/api-docs
        name: CONTRACT Service
        display-name: CONTRACT Service