apiVersion: v1
kind: Service
metadata:
  namespace: sgma-system
  name: discovery-service-service
  labels:
    app: discovery-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8761
  selector:
    app: discovery-service
  #type: NodePort