spring:
  application:
    name: '${SPRING_APPLICATION_NAME:loan-service}'
  datasource:
    driverClassName: '${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}'
    url: '${SPRING_DATASOURCE_URL:jdbc:h2:mem:loandb}'
    username: '${SPRING_DATASOURCE_USERNAME:admin}'
    password: '${SPRING_DATASOURCE_PASSWORD:admin}'
  jpa:
    database-platform: '${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}'
    hibernate:
      ddl-auto: '${SPRING_JPA_HIBERNATE_DDL_AUTO:update}'
  mail:
    host: '${SPRING_MAIL_HOST:smtp.gmail.com}'
    port: '${SPRING_MAIL_PORT:587}'
    username: '${SPRING_MAIL_USERNAME:rabiiyahya10@gmail.com}'
    password: '${SPRING_MAIL_PASSWORD:ewrh gkab unnu bjir}'
    properties:
      mail:
        smtp:
          auth: '${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}'
          starttls:
            enable: '${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:true}'
          from: '${SPRING_MAIL_PROPERTIES_MAIL_FROM:custom.sender@example.com}'
  h2:
    console:
      enabled: '${SPRING_H2_CONSOLE_ENABLED:true}'
      path: '${SPRING_H2_CONSOLE_PATH:/h2-console}'
      settings:
        web-allow-others: '${SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS:false}'
minio:
  server:
    url: '${MINIO_SERVER_URL:http://localhost:9000}'
    username: '${MINIO_ACCESS_USERNAME:noxideuxTheGoat}'
    password: '${MINIO_ACCESS_SECRET:noxideux11102001noxideux}'
  bucket:
    name: '${MINIO_BUCKET_NAME:loan-service}'
  domain: '${MINIO_DOMAIN:http://localhost:9000/}'
  
  cloud:
    kubernetes:
      enabled: true
        #reload:
        #enabled: true
        #mode: event
        #strategy: shutdown
        #config:
        #sources:
          #- namespace: common
            #name: environment
          #- name: gestion
      discovery:
        enabled: true
        namespace: sgma-system
        #namespaces:
        #  - sgma-system
        #  - namespace2
        #  - namespace3
        #all-namespaces: true
eureka:
  client:
    enabled: false
    config:
      enabled: false
    discovery:
      enabled: '${SPRING_CLOUD_DISCOVERY_ENABLED:true}'
server:
  port: '${SERVER_PORT:8082}'
management:
  endpoints:
    web:
      exposure:
        include: '${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:*}'
  endpoint:
    health:
      show-details: '${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:always}'
logging:
  file:
    path: '${LOGGING_FILE_PATH:C:/Users/yahyarb/Desktop/Loggs}'
openapi:
  service:
    title: '${OPENAPI_SERVICE_TITLE:LOAN-SERVICE doc}'
    version: '${OPENAPI_SERVICE_VERSION:1.0.0}'
    url: '${OPENAPI_SERVICE_URL:http://localhost:8888}'
springdoc:
  api-docs:
    path: '${SPRINGDOC_API_DOCS_PATH:/loan-service/v3/api-docs}'
  swagger-ui:
    path: '${SPRINGDOC_SWAGGER_UI_PATH:/loan-service/swagger-ui.html}'
getclient:
  Byid:
    endpoint: '${GETCLIENT_BYID_ENDPOINT:/client/}'
client:
  service:
    url: '${CLIENT_SERVICE_URL:http://localhost:8888/client-service}'
project:
  id: '${PROJECT_ID:soge-sign}'
folder:
  name: '${FOLDER_NAME:soge/}'
