apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-configmap
  namespace: {{ .Values.namespace }}
data:
  SPRING_CLOUD_GATEWAY_ROUTES_CLIENT_SERVICE_METADATA_CORS_ALLOWED_ORIGINS: {{ .Values.data.SPRING_CLOUD_GATEWAY_ROUTES_CLIENT_SERVICE_METADATA_CORS_ALLOWED_ORIGINS | quote }}
  SPRING_CLOUD_GATEWAY_ROUTES_LOAN_SERVICE_METADATA_CORS_ALLOWED_ORIGINS: {{ .Values.data.SPRING_CLOUD_GATEWAY_ROUTES_LOAN_SERVICE_METADATA_CORS_ALLOWED_ORIGINS | quote }}
  SPRING_CLOUD_GATEWAY_ROUTES_CONTRACT_SERVICE_METADATA_CORS_ALLOWED_ORIGINS: {{ .Values.data.SPRING_CLOUD_GATEWAY_ROUTES_CONTRACT_SERVICE_METADATA_CORS_ALLOWED_ORIGINS | quote }}
  SPRING_CLOUD_GATEWAY_ROUTES_AUTH_SERVICE_METADATA_CORS_ALLOWED_ORIGINS: {{ .Values.data.SPRING_CLOUD_GATEWAY_ROUTES_AUTH_SERVICE_METADATA_CORS_ALLOWED_ORIGINS | quote }}
  SPRING_CLOUD_GATEWAY_ROUTES_ACCOUNT_SERVICE_METADATA_CORS_ALLOWED_ORIGINS: {{ .Values.data.SPRING_CLOUD_GATEWAY_ROUTES_ACCOUNT_SERVICE_METADATA_CORS_ALLOWED_ORIGINS | quote }}
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://{{ .Values.keycloak.name }}-service.{{ .Values.keycloak.namespace }}.svc.cluster.local/realms/{{ .Values.keycloak.realm }}"