apiVersion: v1
kind: Service
metadata:
  namespace: sgma-system
  name: gateway-service
  labels:
    app: gateway-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8888
  selector:
    app: gateway-service