apiVersion: v1
kind: Service
metadata:
  namespace: sgma-system
  name: contract-service
  labels:
    app: contract-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8083
  selector:
    app: contract-service
  #type: NodePort