apiVersion: v1
kind: Service
metadata:
  namespace: sgma-system
  name: client-service-service
  labels:
    app: client-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8084
  selector:
    app: client-service
  #type: NodePort