apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minio
  name: minio-deployment
  namespace: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: bitnami/minio:2024.4.6-debian-12-r0
        ports:
        - containerPort: 9000
        - containerPort: 9001
        env:
        - name: MINIO_ROOT_USER
          value: "noxideuxTheGoat"
        - name: MINIO_ROOT_PASSWORD
          value: "noxideux11102001noxideux"
        - name: MINIO_DEFAULT_BUCKETS
          value: "loan-service"


        volumeMounts:
        - name: host-etc
          mountPath: "/certs"
      volumes:
      - name: host-etc
        hostPath:
          path: "/etc/tls"
