apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-configmap
  namespace: sgma-system
data:
 
  KEYCLOAK_AUTH_SERVER_URL: "http://keycloak-service.keycloak.svc.cluster.local/admin/realms/AppCC-realm/"
  KEYCLOAK_AUTH_GET_ROLES_ENDPOINT: "roles"
  KEYCLOAK_AUTH_GETORCREATE_USERS_ENDPOINT: "users"
  KEYCLOAK_REALM: "AppCC-realm"
  KEYCLOAK_RESOURCE: "AppCC-client"
  KEYCLOAK_CREDENTIALS_SECRET: "2daZvH7aBBVcwI9mvJw3dPQMwWUiZhVK"
  KEYCLOAK_TOKEN_URL: "http://keycloak-service.keycloak.svc.cluster.local/realms/AppCC-realm/protocol/openid-connect/token"
  KEYCLOAK_LOGOUT_URL: "http://keycloak-service.keycloak.svc.cluster.local/admin/realms/AppCC-realm/users/UserId/logout"
  KEYCLOAK_USER_ROLES_URL: "http://keycloak-service.keycloak.svc.cluster.local/admin/realms/AppCC-realm/users/UserId/role-mappings/realm"
  CLIENT_SERVICE_URL: "http://gateway-service-service.sgma-system.svc.cluster.local/client-service"
  EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: "http://discovery-service-service.sgma-system.svc.cluster.local/eureka/"
  CUSTOM_CONFIG_URL: "optional:configserver:http://config-service-service.sgma-system.svc.cluster.local"