apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-configmap
  namespace: sgma-system
data:
  SPRING_APPLICATION_NAME: "auth-service"
  SERVER_PORT: "8081"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.h2.Driver"
  SPRING_DATASOURCE_URL: "jdbc:h2:mem:authdb"
  SPRING_DATASOURCE_USERNAME: "admin"
  SPRING_DATASOURCE_PASSWORD: "admin"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.H2Dialect"
  SPRING_H2_CONSOLE_ENABLED: "true"
  SPRING_H2_CONSOLE_PATH: "/h2-console"
  SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS: "false"
  SPRING_CLOUD_DISCOVERY_ENABLED: "true"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  LOGGING_FILE_PATH: "C:/Users/yahyarb/Desktop/Loggs"
  OPENAPI_SERVICE_TITLE: "AUTH-SERVICE doc"
  OPENAPI_SERVICE_VERSION: "1.0.0"
  OPENAPI_SERVICE_URL: "http://localhost:8888"
  SPRINGDOC_API_DOCS_PATH: "/auth-service/v3/api-docs"
  SPRINGDOC_SWAGGER_UI_PATH: "/auth-service/swagger-ui.html"
  KEYCLOAK_AUTH_SERVER_URL: "http://localhost:8080/admin/realms/${keycloak.realm}/"
  KEYCLOAK_AUTH_GET_ROLES_ENDPOINT: "roles"
  KEYCLOAK_AUTH_GETORCREATE_USERS_ENDPOINT: "users"
  KEYCLOAK_REALM: "AppCC-realm"
  KEYCLOAK_RESOURCE: "AppCC-client"
  KEYCLOAK_CREDENTIALS_SECRET: "2daZvH7aBBVcwI9mvJw3dPQMwWUiZhVK"
  KEYCLOAK_TOKEN_URL: "http://localhost:8080/realms/${keycloak.realm}/protocol/openid-connect/token"
  KEYCLOAK_LOGOUT_URL: "http://localhost:8080/admin/realms/${keycloak.realm}/users/UserId/logout"
  KEYCLOAK_USER_ROLES_URL: "http://localhost:8080/admin/realms/${keycloak.realm}/users/UserId/role-mappings/realm"
  CLIENT_SERVICE_URL: "http://localhost:8888/client-service"
  CREATECLIENT_ENDPOINT: "/createClient"
  GETCLIENT_BYID_ENDPOINT: "/client/"
  UPDATECLIENT_BYID_ENDPOINT: "/updateClient/"
  CUSTOM_CONFIG_URL: "optional:configserver:http://localhost:9999"