spring:
  application:
    name: ${DISCOVERY_SERVICE_NAME:discovery-service}
    
eureka:
  client:
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY:false}
    registryFetchIntervalSeconds: ${EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL_SECONDS:5}
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:false}
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
  
server:
  port: ${SERVER_PORT:8761}