apiVersion: v1
kind: Service
metadata:
  name: socgen-ui-service
  namespace: sgma-system
  labels:
    app: socgen-ui
spec:
  selector:
    app: socgen-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80