apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appName }}-deployment
spec:
  replicas: {{ .Values.spec.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: salaheddine122/soge-system-client-service:CLIENT-SERVICE-v2.0.0
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: {{ .Values.appName }}-configmap
          - configMapRef:
              name: {{ .Values.activeProfile }}-configmap
        ports:
        - containerPort: 8084

        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8084
          initialDelaySeconds: 10
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8084
          initialDelaySeconds: 10
          periodSeconds: 10
