- name: update packages
  dnf:
    name: '*'
    state: latest
    update_cache: yes

- name: Disable swap for current session
  command: swapoff -a

- name: Permanently remove swap
  command:
    cmd: sed -i '/ swap / s/^/#/' /etc/fstab

- name: Set SELinux in permissive mode (disabling it)
  ansible.posix.selinux:
    policy: targeted
    state: permissive

- name: Set SELinux in permissive mode (disabling it)2
  command:
    cmd: sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

# Adjust the KUBE_VERSION var to pick your kubernetes version
- name: overwrites existing configuration in /etc/yum.repos.d/kubernetes.repo
  copy:
    dest:  /etc/yum.repos.d/kubernetes.repo
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://pkgs.k8s.io/core:/stable:/{{ KUBE_VERSION }}/rpm/
      enabled=1
      gpgcheck=1
      gpgkey=https://pkgs.k8s.io/core:/stable:/{{ KUBE_VERSION }}/rpm/repodata/repomd.xml.key
      exclude=kubelet kubeadm kubectl cri-tools kubernetes-cni

- name: Install kubelet, kubeadm and kubectl
  dnf:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present 
    disable_excludes:  kubernetes

- name: enable kubelet
  systemd:
    name:  kubelet
    state: restarted
    enabled:  true

- name: Ensure br_netfilter kernel modules is loaded, if not load it and ensure it's loaded on boot
  community.general.modprobe:
    name: br_netfilter
    state: present
    persistent: present

- name: Ensure overlay kernel modules is loaded, if not load it and ensure it's loaded on boot
  community.general.modprobe:
    name: overlay
    state: present
    persistent: present

- name: Ensure net.bridge.bridge-nf-call-iptables is set to 1
  ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    sysctl_set: true
    state: present

- name: Ensure net.bridge.bridge-nf-call-ip6tables is set to 1
  ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: 1
    sysctl_set: true
    state: present

- name: Ensure net.ipv4.ip_forward is set to 1
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: true
    state: present

- name: Ensure net.ipv4.ip_forward, net.bridge.bridge-nf-call-iptables and net.bridge.bridge-nf-call-ip6tables are set on boot
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: "{{ item }}"
    create: true
    owner: root
    group: root
    mode: "0644"
  loop:
    - net.ipv4.ip_forward=1
    - net.bridge.bridge-nf-call-iptables=1
    - net.bridge.bridge-nf-call-ip6tables=1

#- name: Add Docker CE repository
#  yum_repository:
#    name: docker-ce
#    description: Docker CE Stable - $basearch
#    baseurl: https://download.docker.com/linux/centos/9/$basearch/stable
#    gpgcheck: yes
#    gpgkey: https://download.docker.com/linux/centos/gpg
#    repo_gpgcheck: yes


#- name: Update containerd config
#  command:
#    cmd:  sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml

#- name: Start containerd
#  systemd:
#    name:  containerd
#    state: restarted
#    enabled: true
