- name: Generate and save token
  command: kubeadm token create
  register: token_output
  when: inventory_hostname == MAIN_CONTROLPLANE


- name: Save token in a variable
  set_fact:
    token: "{{ token_output.stdout }}"
  when: inventory_hostname == MAIN_CONTROLPLANE
  
- name: Generate and save CA cert hash
  shell: "openssl x509 -in /etc/kubernetes/pki/ca.crt -noout -pubkey | openssl rsa -pubin -outform DER 2>/dev/null | sha256sum | cut -d' ' -f1"
  register: ca_cert_hash_output
  when: inventory_hostname == MAIN_CONTROLPLANE

- name: Save CA cert hash in a variable
  set_fact:
    ca_cert_hash: "{{ ca_cert_hash_output.stdout }}"
  when: inventory_hostname == MAIN_CONTROLPLANE

- name: Generate and save private key
  shell: "openssl rsa -in /etc/kubernetes/pki/ca.key -outform DER -out /tmp/ca.key 2>/dev/null"
  when: inventory_hostname == MAIN_CONTROLPLANE

- name: Generate tmp private key content
  shell: kubeadm init phase upload-certs --upload-certs 2>&1 | grep -oE "[0-9a-f]{64}" | awk 'NR==1'
  register: private_key_output
  when: inventory_hostname == MAIN_CONTROLPLANE
  
- name: Save private key content in a variable
  set_fact:
    private_key: "{{ private_key_output.stdout }}"
  when: inventory_hostname == MAIN_CONTROLPLANE

- name: generate domain
  shell: kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}' | sed 's/^https:\/\///'
  register: domain_output
  when: inventory_hostname == MAIN_CONTROLPLANE

- name: Save my domain with port in a variable
  set_fact:
    domain: "{{ domain_output.stdout }}"
  when: inventory_hostname == MAIN_CONTROLPLANE

- name: save vars in second host
  set_fact:
    transferred_token: "{{ hostvars[MAIN_CONTROLPLANE].token }}"
    transferred_ca_cert_hash: "{{ hostvars[MAIN_CONTROLPLANE].ca_cert_hash }}"
    transferred_domain: "{{ hostvars[MAIN_CONTROLPLANE].domain }}"
    transferred_private_key: "{{ hostvars[MAIN_CONTROLPLANE].private_key }}"
  when: inventory_hostname != MAIN_CONTROLPLANE

- name: Add control plane
  shell: "kubeadm join {{ transferred_domain }} --token {{ transferred_token }} --discovery-token-ca-cert-hash sha256:{{ transferred_ca_cert_hash }} --control-plane --certificate-key {{ transferred_private_key }}"
  when: inventory_hostname != MAIN_CONTROLPLANE