apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin-service-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sgma-system
    server: "https://kubernetes.default.svc"
  project: socgen-project
  source:
    path: helm-charts/admin-service-chart/
    repoURL: git@github.com:Yahya-rabii/SGMA-System.git
    targetRevision: master
    helm:
      valueFiles:
        - values-dev.yaml
  syncPolicy:
    #automated:
      #prune: false
      #selfHeal: false
    syncOptions:
      - CreateNamespace=false
