server:
  port: 8888
  servlet:
    context-path: /
spring:
  application:
    name: Gateway
  cloud:
    gateway:
        routes:
          - id: client-service
            uri: lb://CLIENT-SERVICE
            predicates:
              - Path=/CLIENT-SERVICE/**
          - id: contract-service
            uri: lb://CONTRACT-SERVICE
            predicates:
              - Path=/CLIENT-SERVICE/**
          - id: AUTH-SERVICE
            uri: lb://AUTH-SERVICE
            predicates:
              - Path=/AUTH-SERVICE/**
    discovery:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/AppCC-realm
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: Gateway
        display-name: Gateway
      - url: /CLIENT-SERVICE/v3/api-docs
        name: CLIENT Service
        display-name: CLIENT Service
      - url: /CONTRACT-SERVICE/v3/api-docs
        name: CONTRACT Service
        display-name: CONTRACT Service
      - url: /AUTH-SERVICE/v3/api-docs
        name: Auth Service
        display-name: Auth Service

