- name: Run kubeinit to start the control plane
  command:
    cmd: sudo kubeadm init --pod-network-cidr={{ IP_ADDRESS_RANGE }} --control-plane-endpoint={{ inventory_hostname }}.socgen.local

- name: Create .kube directory if it doesn't exist
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory

- name: Copy kube-config to home directory
  copy:
    dest:  "{{ ansible_env.HOME }}/.kube/config"
    src:  /etc/kubernetes/admin.conf
    remote_src: yes

- name: Ensure ~/.kube/config ownership is set
  file:
    path: "{{ ansible_env.HOME }}/.kube/config"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Install Git
  dnf:
    name: git
    state: latest 
    update_cache: yes

- name: Download Helm script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0700'

- name: Run Helm installation script
  command: /tmp/get_helm.sh


