- name: Setup additions on all nodes
  hosts: ALL_VMS
  roles:
    - roles/initialization/add_to_host
  become: true

- name: Download Setup nginx load balancers
  hosts: LOAD_BALANCERS
  roles:
    - roles/load-balancer/nginx
