server:
  port: 9999

spring:
  cloud:
    discovery:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/Yahya-rabii/configrepo.git
          username: Yahya-rabii
          password: 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
          default-label: "master"
  application:
    name: CONFIG-SERVER


# layrhem lwalidin mathakiwnich  ra ghadi nhiyed token mn be3d