server:
  port: 9999

spring:
  cloud:
    discovery:
      enabled: true
    config:
      server:
        git:
          uri: file:///C:/Users/yahyarb/Desktop/configurationrepo
          username: Yahya-rabii
          password: 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
          default-label: "master"
  application:
    name: CONFIG-SERVER


