server:
  port: 9999

spring:
  cloud:
    discovery:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/Yahya-rabii/configrepo.git
          username: Yahya-rabii
          password: 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
          default-label: "master"
  application:
    name: config-server


