server:
  port: ${SERVER_PORT:9999}


spring:
  cloud:
    discovery:
      enabled: ${DISCOVERY_ENABLED:false}
    config:
      server:
        native:
          search-locations: ${CONFIG_SEARCH_LOCATIONS:file:///C:/Users/yahyarb/Desktop/configrepo}
        git:
          uri: ${CONFIG_GIT_URI:https://github.com/Yahya-rabii/configrepo.git}
          username: ${CONFIG_GIT_USERNAME:Yahya-rabii}
          password: ${CONFIG_GIT_PASSWORD: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}
          default-label: ${CONFIG_GIT_DEFAULT_LABEL:master}
        bootstrap: true
      allow-override: true
      override-none: false
  application:
    name: ${SPRING_APPLICATION_NAME:config-server}
  profiles:
    default: ${ACTIVE_PROFILE:native}

eureka:
  client:
    registryFetchIntervalSeconds: ${EUREKA_REGISTRY_FETCH_INTERVAL_SECONDS:5}
    registerWithEureka: ${EUREKA_REGISTER_WITH_EUREKA:true}
    fetchRegistry: ${EUREKA_FETCH_REGISTRY:true}
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}

