server:
  port: 9999

spring:
  cloud:
    discovery:
      enabled: true
    config:
      server:
        git:
          uri: file:///C:/Users/yahyarb/Desktop/configurationrepo #https://github.com/Yahya-rabii/configrepo.git
          #username: Yahya-rabii
          #password: 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
          default-label: "master"
  application:
    name: CONFIG-SERVER


# layrhem lwalidin mathackiwnich  ra ghadi nhiyed token mn be3d