server:
  port: 9999

spring:
  cloud:
    discovery:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/Yahya-rabii/configrepo.git
          username: Yahya-rabii
          password: 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
          default-label: "master"
  application:
    name: config-server

eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
