server:
  port: ${SERVER_PORT:8765}

spring:
  boot:
    admin:
      discovery:
        ignored-services: ${SPRING_BOOT_ADMIN_DISCOVERY_IGNORED_SERVICES:gateway-service}

eureka:
  client:
    registryFetchIntervalSeconds: ${EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL_SECONDS:5}
    registerWithEureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:true}
    fetchRegistry: ${EUREKA_CLIENT_FETCH_REGISTRY:true}
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka/}
#eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
eureka.instance.prefer-ip-address: true