#apiVersion: v1
#kind: Service
#metadata:
#  namespace: minio
#  name: minio-service
#  labels:
#    app: minio
#spec:
#  selector:
#    app: minio
#  ports:
#    - protocol: TCP
#      name: "dashboard-port"
#      port: 80
#      targetPort: 9001

#    - protocol: TCP
#      name: "internal-port"
#      port: 9000
#      targetPort: 9000

#  type: NodePort
