apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuerName }}
spec:
  ingressClassName: {{ .Values.ingress.ingressName }}
  tls:
    - hosts:
        - {{ .Values.ingress.ingressHostname }}
      secretName: {{ .Values.ingress.tlsGeneratedSecretName }}
  rules:
    - host: {{ .Values.ingress.ingressHostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.appName }}-service
                port:
                  number: 443