apiVersion: v1
kind: Service
metadata:
  namespace: sgma-system
  name: config-service-service
  labels:
    app: config-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9999
  selector:
    app: config-service
  #type: NodePort