name: Soge-system-esignature-service pipeline # changes depending on service

on:
  push:
    tags:
      - 'ESIGNATURE-SERVICE-v*'

      
env:
  SERVICE_NAME: soge-system-esignature-service # changes depending on service
  REGISTRY_NAME: salaheddine122/
  APP_CONTEXT: AppCC-back/Esignature # changes depending on service

jobs:
  explore_github_actions:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
  
  java_setup_and_tests:
    needs: explore_github_actions
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Clean everything
        run: cd ${{ env.APP_CONTEXT }} && mvn clean

      - name: Compile main code
        run: cd ${{ env.APP_CONTEXT }} && mvn compile

      - name: Create artifact
        run : cd ${{ env.APP_CONTEXT }} && mvn package -DskipTests

  scan_vulnerabilities_image:
    needs: java_setup_and_tests
    runs-on: ubuntu-latest
    steps:
      - name: Scan for vulnerabilities first build phase
        uses: crazy-max/ghaction-container-scan@v3.0.0
        with:
          image: maven:3.8.4-openjdk-17
      
      - name: Scan for vulnerabilities second build phase
        uses: crazy-max/ghaction-container-scan@v3.0.0
        with:
          image: openjdk:17-jdk-alpine
        
  build_and_push_docker_images:
    needs: scan_vulnerabilities_image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3 

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          push: true
          tags: ${{ env.REGISTRY_NAME }}${{ env.SERVICE_NAME }}:${{ github.ref_name }}
          context: ${{ env.APP_CONTEXT }}