name: Soge-system-UI pipeline

on:
  push:
    tags:
      - 'UI-v*' 
    branches:
      - master
   
env:
  SERVICE_NAME: soge-system-ui
  REGISTRY_NAME: salaheddine122/
  APP_CONTEXT: AppCC-front/
  ARTEFACT_NAME: front-app-cc
jobs:
  explore_github_actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

  build_and_push_docker_images:
    needs: explore_github_actions
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3 

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          push: true
          tags: ${{ env.REGISTRY_NAME }}${{ env.SERVICE_NAME }}:${{ github.ref_name }}
          context: ${{ env.APP_CONTEXT }}
          build-args: |
              name=${{ env.ARTEFACT_NAME }}
          